services:
  - type: web
    name: bookmanagment-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
    startCommand: |
      php artisan migrate --seed --force
      php artisan serve --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: your-database-name
          property: host
      - key: DB_PORT
        fromDatabase:
          name: your-database-name
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: your-database-name
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: your-database-name
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: your-database-name
          property: password
